changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: New Features 🎉
      labels:
        - enhancement
        - feature
    - title: Bug Fixes 🐛
      labels:
        - bug
        - fix
    - title: Documentation 📚
      labels:
        - documentation
        - docs
    - title: Distribute & Release 📦
      labels:
        - release
        - distribute
        - ci
    - title: Other Changes
      labels:
        - "*"
